spring.application.name=ai-service


server.port=8091

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.1

management.endpoints.web.exposure.include=health,info
