spring.application.name=Eureka-server

server.port = 8761

# Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional
eureka.server.enable-self-preservation=true

# Eureka dashboard
eureka.instance.hostname=localhost

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true